services:
  volatility3-mcp-server:
    image: ghcr.io/capelabs/volatility3-mcp-server:latest
    restart: always
    container_name: volatility3-mcp-server
    ports:
      - "8000:8000"
    volumes:
      - ./volatility3-mcp-server/dumps:/app/dumps
  logstash:
    image: docker.elastic.co/logstash/logstash:9.0.0
    restart: always
    container_name: logstash
    environment:
      - MONITORING_ENABLED=false
      - LS_JAVA_OPTS=-Xmx2g -Xms2g
    ports:
      - "5044:5044"
      - "5045:5045"
    command: bash -c "bin/logstash-plugin install logstash-output-opensearch && logstash -f /usr/share/logstash/pipeline/logstash.conf"
    volumes:
      - ./configs/logstash/pipeline:/usr/share/logstash/pipeline
      - ./configs/logstash/config:/usr/share/logstash/config
    depends_on:
      - opensearch
    networks:
      - opensearch_network
  opensearch:
    image: ghcr.io/capelabs/opensearch-mcp-server:latest
    restart: always
    container_name: opensearch
    environment:
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - opensearch_data:/usr/share/opensearch/data
      - ./configs/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    networks:
      - opensearch_network
    ports:
      - "9200:9200"
  opensearch_dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    restart: always
    container_name: opensearch_dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    networks:
      - opensearch_network
  enable_mcp_server:
    image: alpine/curl:latest
    container_name: enable_mcp_server
    volumes:
      - $PWD/scripts:/scripts
    depends_on:
      - opensearch
    command: sh -c "chmod +x /scripts/enable-mcp-server.sh && sh /scripts/enable-mcp-server.sh"
    networks:
      - opensearch_network
volumes:
  opensearch_data:
    driver: local
networks:
  opensearch_network:
    driver: bridge
