name: Build and Push Docker Volatility3 MCP Image

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get build timestamp
        id: get_timestamp
        run: echo "BUILD_TIMESTAMP=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: |
            linux/amd64
            linux/arm64
          context: ./volatility3-mcp-server
          file: ./volatility3-mcp-server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/volatility3-mcp-server:latest
            ghcr.io/${{ github.repository_owner }}/volatility3-mcp-server:${{ env.BUILD_TIMESTAMP }}
          build-args: |
            BUILD_TIMESTAMP=${{ env.BUILD_TIMESTAMP }}
